### ISSUE TITLE
DSK to directory conversion not finding volume name increment and failing.

### ISSUE THREAD

**Issue by jedimatt42** [jedimatt42/tipi#142]
https://atariage.com/forums/topic/277635-tipi-usage-and-support/?do=findComment&comment=4630941

**Comment by jedimatt42** [comment]
Something about this code is borken :  https://github.com/jedimatt42/tipi/blob/1ea33e66d7209a47d5defbbee2fe5d7da24af3aa/htdocs/dsks/extract_sectordump.py#L37

**Comment by webdeck** [comment]
Replace `return string.join(parts, "_")` with `return "_".join(parts)`

**Comment by jedimatt42** [comment]
fixed in https://github.com/jedimatt42/tipi/commit/56511a72d6a34880d07cd28824580ec089726594
version 2.7
