### ISSUE TITLE
when extracting files from DSK image and the filename has an * in it.. fails

### ISSUE THREAD

**Issue by arcadeshopper** [jedimatt42/tipi#171]
xdm99.py DISK-030A-Fiddler_ASGD.dsk -t -e FIDDLER* -o DISK-030/FIDDLER
Error: -o must provide directory when extracting multiple files

**Comment by jedimatt42** [comment]
<img width="393" alt="image" src="https://github.com/jedimatt42/tipi/assets/3005167/40cf9c8d-a4a6-46af-9153-d21c7f175088">

With a DSK file created in TI99DIR with the the `*` in several positions of the file names, they extract fine on TIPI.

<img width="530" alt="image" src="https://github.com/jedimatt42/tipi/assets/3005167/d659b98b-7f46-4f21-8f06-a15f7b9798a7">

When I pass the file name to the xdm99 command I use an arg list, so no shell is processing the wildcard... I suspect your command would have worked if you had wrapped the FIDDLER* in single quotes such as `'FIDDLER*'`
