### ISSUE TITLE
when editing a text file on the ti, changes aren't written to the file completely

### ISSUE THREAD

**Issue by arcadeshopper** [jedimatt42/tipi#86]
using ea editor and preditor both i removed 50 lines from a text file and saved it only to find the lines still there on the file.. my specific line changes seemed to save at the top, but the erased lines did not

**Comment by jedimatt42** [comment]
That's a cool bug! We could have gone years without noticing that.

**Comment by arcadeshopper** [comment]
additional info, when editing a file with ea editor it seems to add a bunch of garbage to the eof as well I just "saved as" auto-bat2 with my shortened file, that worked fine.. (ie creating a new file works) I just renamed the files so that was my auto-bat file.. But then I edited the new file to switch the order of events and got this after saving:  
![image](https://user-images.githubusercontent.com/34459018/35451535-6a5db51e-0278-11e8-8194-0c23d04cd992.png)

**Comment by jedimatt42** [comment]
fixed

**Comment by arcadeshopper** [comment]
still getting the same garbage in the file as above
