### ISSUE TITLE
UnicodeDecodeError when opening Extended basic loader for Infocom games in web

### ISSUE THREAD

**Issue by arcadeshopper** [jedimatt42/tipi#87]
clicked on the view program icon and got that error

**Comment by jedimatt42** [comment]
I fixed this on master... will be in next release... TI BASIC can be riddled with embedded control characters, outside the range of ascii... ascii is only 32-127   so utf-8 decoding doesn't know what to do with bytes with value 128... 

So, we decode from a character set with a full range of 0-255 like latin_1.   and re-encode to latin_1 when saving from the editor... Characters look funny... but they show up as blanks on the TI anyway, unless they have been custom defined.

Fixed.
